# Generated by Django 4.1.4 on 2023-03-05 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agent",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="lead",
            name="address",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Gaza", "Gaza"),
                    ("North Gaza", "North Gaza"),
                    ("Central", "Central"),
                    ("Khan Yunis", " Khan Yunis"),
                    ("Rafah", "Rafah"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
