# Generated by Django 4.1.4 on 2023-03-05 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_agent_profile_image_alter_lead_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agent",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                default="profiles/default-profile.png",
                null=True,
                upload_to="profiles/",
            ),
        ),
    ]
