# Generated by Django 4.1.4 on 2023-03-07 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="plan",
            old_name="price",
            new_name="cost",
        ),
        migrations.RemoveField(
            model_name="client",
            name="user",
        ),
        migrations.AddField(
            model_name="plan",
            name="description",
            field=models.TextField(
                blank=True, help_text="enter details", max_length=500, null=True
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="duration",
            field=models.DurationField(
                choices=[
                    ("6 months", 6),
                    ("3 months", 3),
                    ("12 months", 12),
                    ("1 month", 1),
                ]
            ),
        ),
    ]
